### ISSUE TITLE
WinToast Library Creates Shortcut in Start Menu

### ISSUE THREAD

**Issue by joshorenberg** [mohabouje/WinToast#106]
Hi every time I initialize WinToast using the sample initialization code from Shao Voon Wong's codeproject.com writeup it creates a shortcut in the start menu to the program exe. In my opinion this is undesirable behavior. Is there a way around this? Thanks! Sample code below.

```
void Replicator::initToast()
{
    WinToast::WinToastError error;
    WinToast::instance()->setAppName(L"Program");
    const auto aumi = WinToast::configureAUMI
    (L"Program", L"Program", L"Program", L"1.5.0");
    WinToast::instance()->setAppUserModelId(aumi);

    if (!WinToast::instance()->initialize(&error))
        emit updateStatus(StatusType::error, "Failed to initialize WinToast: " + QString::number(int(error)));
}
```

**Comment by joshorenberg** [comment]
Solution is:
WinToast::instance()->setShortcutPolicy(WinToast::SHORTCUT_POLICY_IGNORE);

**Comment by ChristianGalla** [comment]
Without a valid shortcut including a special property installed in the Start screen or in All Programs, you cannot raise a toast notification from a desktop app.
This library ensures a valid shortcut exists.

However, Microsoft recommends creating the shortcut through an installer and not through application code.

https://learn.microsoft.com/en-us/windows/win32/shell/enable-desktop-toast-with-appusermodelid

**Comment by mohabouje** [comment]
I'm closing this issue. As @ChristianGalla said, the library will attempt to create a valid shortcut by default. If your application provides a valid shortcut, the policy can be changed to avoid this step.
