### ISSUE TITLE
WinToast::initialize() always returns false

### ISSUE THREAD

**Issue by sraboy** [mohabouje/WinToast#24]
I imagine [this line](https://github.com/mohabouje/WinToast/blob/f2850f2d0088d15fbb18427e13643400e32562b8/src/wintoastlib.cpp#L404) is supposed to be `return true;` at this point, right?

**Comment by mohabouje** [comment]
I was a little bit busy this week and I did not have time to check the problem with the initialize function! Thank you man!

**Comment by mohabouje** [comment]
The function is suppose to return the state of the _isInitialized variable, see the quick fix: https://github.com/mohabouje/WinToast/commit/6b5c0c64c87ce9376118fd390fd2e3a1f339b29b

**Comment by sraboy** [comment]
Thanks!
