### ISSUE TITLE
Add Custom XML

### ISSUE THREAD

**Issue by sraboy** [mohabouje/WinToast#25]
Do you know how to add new elements and or add attributes to an element? I cannot for the life of me figure that out. 

I resorted to using `IXmlDocumentIO::LoadXml("[xmlhere]")` and its `ComPtr::CopyTo([the IXmlDocument])` but that makes using all your helpers to set text/image impossible.

For now, I've hacked in two new `WinToastTemplateType` values (`CustomXmlText` and `CustomXmlImageAndText`) but, if you know how to add new elements and attributes to existing elements, it would be a great feature add.

Here's an example XML template I'm using:
```
<toast duration="short">
   <audio silent="true" />
   <visual>
      <binding template="ToastGeneric">
         <image placement="appLogoOverride" hint-crop="circle" src="" />
         <text hint-maxLines="1" />
         <text placement="attribution">via SMS</text>
      </binding>
   </visual>
</toast>
```

_Side note, if you do start messing with this, putting XML in the command-line arguments in VS' project settings results in single quotes being swapped for double quotes and an `xmlns` attribute being added to the first element once you hit "Apply". After it edits it, you have to manually escape the double quotes and leave in the `xmlns` attribute._

**Comment by sraboy** [comment]
Aha, finally figured it out. If I can get it cleaned up, would you want a PR to add audio options and attribution text?

**Comment by mohabouje** [comment]
Yeah, definitely . It will be nice as a new feature :) When you get
something ready to test, just do the PR.

**Comment by mohabouje** [comment]
Let's review the PR and close this one then.
