### ISSUE TITLE
Notification count

### ISSUE THREAD

**Issue by Bawabawa01** [mohabouje/WinToast#29]
Hello. Can anyone help me with the notification count on taskbar. When the app is showing the toast, whether user click on toast or ignores it, after a few second it fully disappears, and in Action Center there is "No new notifications".

**Comment by malja** [comment]
@Bawabawa01 Hi, I have similar problem. After x seconds defined in Windows Notification Center settings, all notifications created with this library are dismissed. 

![Default notification Duration](https://www.howtogeek.com/wp-content/uploads/2016/03/ease_of_access.png)

I found a workaround. Call [setExpiration](https://github.com/mohabouje/WinToast/blob/master/src/wintoastlib.h#L69) method of WinToastTemplate:

    // Notification will be preserved in Action Center for 5 minutes
    template.setExpiration(300000);

I think that preserving notification for unlimited time should be a default behavior. Using setExpiration should just limit this time down, not up like in my example.

**Comment by mohabouje** [comment]
@malja Thanks for the update! I think that this issue is very common and It's not related with the library. Maybe we can add it in the main README.md. Feel free to do it if you want to contribute. =)
