### ISSUE TITLE
better toast types naming

### ISSUE THREAD

**Issue by kambala-decapitator** [mohabouje/WinToast#3]
A toast can have max 3 lines of text, but there're misleading templates ImageWithFourLines and TextFourLines.

Other templates can also be named better to reflect their purpose.

**Comment by mohabouje** [comment]
You are right!

I used names based on the Microsoft documentation (https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Notifications.ToastTemplateType). Probably, preserve the same names is the better solution to maintain consistency.

**Comment by mohabouje** [comment]
Using the official Microsoft template's names: https://github.com/mohabouje/WinToast/commit/62cc13818f2987f1b38095aa900146c97feb8871
