### ISSUE TITLE
Is there any way to stop WinToast from printing to the console?

### ISSUE THREAD

**Issue by Austen-Oberheu** [mohabouje/WinToast#36]
Every notification prints an XML object to the console, is there anyway to stop it from doing that?

**Comment by malja** [comment]
According to this code found in [wintoastlib.cpp](https://github.com/mohabouje/WinToast/blob/master/src/wintoastlib.cpp#L8), just define NDEBUG to stop WinToast from writing to console.

    #ifdef NDEBUG
        #define DEBUG_MSG(str) do { } while ( false )
    #else
        #define DEBUG_MSG(str) do { std::wcout << str << std::endl; } while( false )
    #endif
