### ISSUE TITLE
'auto' must always deduce to the same type

### ISSUE THREAD

**Issue by dedmen** [mohabouje/WinToast#40]
```
wintoastlib.cpp(665): error C3538: in a declarator-list 'auto' must always deduce to the same type
  wintoastlib.cpp(665): note: could be 'unsigned int'
  wintoastlib.cpp(665): note: or       'size_t'
```
Visual Studio 2019 with C++17.

https://github.com/mohabouje/WinToast/blob/master/src/wintoastlib.cpp#L650

`auto` deduces to `unsigned int`, and textFieldsCount returns `size_t` which is `unsigned __int64` on 64bit.
I fixed it by replacing `0u` with `0ull` but that only works because I build x64 only.
On 32bit that would missmatch again.

**Comment by mohabouje** [comment]
Good catch! I should add a note in the documentation to enforce the usage of releases or tagged version.

The current master branch has been modified recently and has not been tested yet in all the different platform.

In this case, probably the easiest solution is to avoid auto and replace it by a simple unsigned type, maybe unsigned long or unsigned int.

**Comment by mohabouje** [comment]
The problem has been fixed in this [commit](https://github.com/mohabouje/WinToast/commit/3a56959e69e2790f2752ac73d0885ad08b96bf46).

**Comment by dedmen** [comment]
Confirmed, all good now.
