### ISSUE TITLE
Can we create Input?

### ISSUE THREAD

**Issue by ghost** [mohabouje/WinToast#42]
Can you add these feautures in this project?
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/images/toast-progressbar.png
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/images/toast-additionaltext.jpg
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/images/adaptivetoasts-buttonswithicons.png
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/images/toast-contextmenu.png
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/images/adaptivetoasts-xmlsample05.jpg

**Comment by mohabouje** [comment]
For sure! I am working right now on another project. As soon as possible I will check the official docs and work a little bit on that. It does not look like a complex, just some xml modifications.

I will publish a new release with the new features mentioned in this [post](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts)

**Comment by lucretius61** [comment]
thank you :))

**Comment by kenkit** [comment]
I vote for a progress bar first

**Comment by mohabouje** [comment]
Sorry for this late response, but I did not work on this project in a while.

We have recently added HeroImage, InlineImage, and CropImage support. I am preparing version 1.4.0 with the backing for InputText, ComboBox selection, and Progress Bar.

**Comment by mohabouje** [comment]
Closing this and adding both features to version 1.4.0: https://github.com/mohabouje/WinToast/issues/86

**Comment by BensonZheng** [comment]
How to get the version 1.4.0, I see the latest version is 1.3.0.
