### ISSUE TITLE
Crash from CoUninitialize/OleUninitialize

### ISSUE THREAD

**Issue by ribtoks** [mohabouje/WinToast#48]
I was trying to use this library from Qt application and there's a conflict between QWindows plugin that also initializes/uninitializes Ole (for `QSystemTrayIcon`). The result of the conflict is that `CoUninitialize()` is called twice and second time it raises an exception (which causes an application).

I don't have a very good solution except to provide a way not to call `CoUninitialize()` in destructor.

**Comment by mohabouje** [comment]
There is a separate issue where different users provide alternative solutions. As you mentioned, there is no clear solution, specially if you use the provided singleton. See [#44](https://github.com/mohabouje/WinToast/issues/44) for more details.
