### ISSUE TITLE
I always get a timeout when running the sample.

### ISSUE THREAD

**Issue by EricYoungdale** [mohabouje/WinToast#53]
I was able to compile and link the sample console application - I ran it using the basic command line in the README.md.   But every time I run the thing, I get a notification that the toast has timed out:

        case TimedOut:
            std::wcout << L"The toast has timed out" << std::endl;
            exit(2);
            break;

There is no delay - I get this immediately, and it does not depend on the settings for the expiration time.

**Comment by mohabouje** [comment]
For future reference, please double-check the system configuration: https://github.com/mohabouje/WinToast#toast-configuration-on-windows-10
