### ISSUE TITLE
IWinToastHandler lacks virtual destructor

### ISSUE THREAD

**Issue by khayk** [mohabouje/WinToast#57]
Custom handlers derived from `IWinToastHandler` and during the `showToast` we provide a raw pointer to that handler, which is internally kept as a smart pointer and destroys then handler by base pointer. This means, that the base class should have a virtual destructor so during the deletion the destructor of the derived class can be called.
Discovered in the version v1.2.0

**Comment by xavery** [comment]
This seems to have been fixed in f0d9708ca3542fdf2be06599ec6edf90e561d2b9.
