### ISSUE TITLE
Example screenshots not visible

### ISSUE THREAD

**Issue by petko** [mohabouje/WinToast#64]
It seems that all examples in the project home page are not visible. I get the "Error Fetching Resource" errors.

**Comment by agashlin** [comment]
The example images can still be found on https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toasttemplatetype?view=winrt-19041, but I don't know if hotlinking to e.g. https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications/images/toast_6.png is going to be any more stable. They can now be found on GitHub at e.g. https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.notifications/images/Toast_6.png, that might be a workable option?

**Comment by petko** [comment]
Thank, that will work!

**Comment by mohabouje** [comment]
I've copied the images from the Microsoft repository to avoid broken links in the future: https://github.com/mohabouje/WinToast/commit/12d7de137613df3de132e14de498a88c63626ba1
