### ISSUE TITLE
Loading Toast Image from Memory

### ISSUE THREAD

**Issue by InactivatedPyschiopath** [mohabouje/WinToast#68]
Is it possible to load icon from memory bitmap? or all the images?

**Comment by mohabouje** [comment]
It seems that there is no apparent workaround for this yet. Most of the time, I end up saving the image into a file and referencing it in the notification:

https://stackoverflow.com/questions/66694454/how-can-i-make-a-notification-in-a-c-sharp-windows-app-with-a-custom-image-and-o
