### ISSUE TITLE
CoUninitialize Exception

### ISSUE THREAD

**Issue by Titan925** [mohabouje/WinToast#70]
I am getting the following exception upon calling the showToast function:
`Exception thrown at 0x00F3FACC in Sample.exe: 0xC0000005: Access violation executing location 0x00F3FACC.`
This was coming from the CoUninitialize() call on line 380 of wintoast.cpp.  

I have tried calling CoInitializeEx() immediately prior to the CoUninitialize() call and it returns S_FALSE as would be expected.

If I continue debugging after the exception, then the toast is displayed successfully.

Any idea what may be causing this behaviour?

**Comment by mohabouje** [comment]
This is a duplicate of this other [issue](https://github.com/mohabouje/WinToast/issues/44). It is a combination of using another dependency that calls CoUninitialize and the late call of CoUninitialize in WinToast singleton destructor. Some workarounds:

- Do not use the singleton
- Call clear before exiting so the destructor does not do much

I am now investigating how to find a robust alternative for this.
