### ISSUE TITLE
Not initializing

### ISSUE THREAD

**Issue by minhook** [mohabouje/WinToast#71]
Don't know if I could be doing anything wrong, using cMake and C++ 17

**Comment by tommywxd** [comment]
Hey there,
Please try the following code so we can know what's going wrong during initialization :)
```
WinToast::WinToastError error;
const bool succedded = WinToast::instance()->initialize(&error);
if (!succedded) {  
    std::wcout << L"Error, could not initialize the lib. Error number: " 
    << error << std::endl;
}
```

**Comment by x64debug** [comment]
> Hey there,
> Please try the following code so we can know what's going wrong during initialization :)
> 
> ```
> WinToast::WinToastError error;
> const bool succedded = WinToast::instance()->initialize(&error);
> if (!succedded) {  
>     std::wcout << L"Error, could not initialize the lib. Error number: " 
>     << error << std::endl;
> }
> ```

thanks big daddy! gonna do it.

**Comment by mohabouje** [comment]
Closing this issue as no extra information was provided
