### ISSUE TITLE
How to add URL to action buttons?

### ISSUE THREAD

**Issue by pranky89** [mohabouje/WinToast#72]
How can I add to open a URL on click of a button ? even when the toast is sitting in the notification center.
Basically, I would like to know how can i modify the arguments of the actions

**Comment by mohabouje** [comment]
Sorry for the late response; I was not active on GitHub for some time. 
Right now, there is no way to change this. I have scheduled this feature to version 1.4.0

I will close this ticket and keep track of this feature here: https://github.com/mohabouje/WinToast/issues/86
