### ISSUE TITLE
Memory leak for long term app run

### ISSUE THREAD

**Issue by step573** [mohabouje/WinToast#75]
Hi there. I need to use WinToast library for long term app run - to show diagnostics information  (eg. 1 week continuous run). After showing thousands of messages there is a significant  growth of memory. Problem is, that method WinToast::clear() is not working, memory is not completely unleashed. I am not expert in Windows API, but I suppose, that windows is holding part of memory when setting the handler (method setEventHandlers() ). I found out, that when EventRegistrationToken (used in setEventHandlers() ) is saved and later used in WinToast::clear()  to call methods of IToastNotification (remove_Activated/remove_Dismissed/remove_Failed), memory is unleashed. Have somone registered the same problem, or is it my misunderstanding how to use the library?

**Comment by shaovoon** [comment]
Hi step573, I have fixed the memory leaks and created a PR. If you cannot wait, you can get it from my article, note there is one break change in showToast(). Read my article on how I fixed the memory leaks and I have added hero image and circle cropped picture feature in my PR.

https://www.codeproject.com/Articles/5286393/Cplusplus-Windows-Toast-Notification

**Comment by LycorisRadiataX** [comment]
Could you please solve this problem?
I also have this situation
I added the output of the destructor in the derived class, but the destructor is only executed when the program exits, and there is a problem with the number of executions

**Comment by shaovoon** [comment]
Hi guys,

The latest code (committed 2 days ago) has fixed the memory leaks. I have documented how I fixed the leaks: 

https://www.codeproject.com/Articles/5286393/Cplusplus-Windows-Toast-Notification#fix_mem_leak

Note: the latest code might differ from my old code in that article.

**Comment by mohabouje** [comment]
Once again, thanks for the great work @shaovoon
