### ISSUE TITLE
Consider putting version at the top of wintoastlib.h/cpp

### ISSUE THREAD

**Issue by shaovoon** [mohabouje/WinToast#78]
Do consider putting the version at the top of the source code (wintoastlib.h/cpp), so that developers can know whether their wintoastlib is out of date.

OT: I found Mozilla is using WinToast at their repo. You can consider adding the Mozilla to "Projects using WinToast" section.

https://hg.mozilla.org/mozilla-central/file/tip/third_party/WinToast/wintoastlib.cpp

**Comment by mohabouje** [comment]
I updated the readme.md file with some extra applications using this library and added a version number to the library's header.
