### ISSUE TITLE
Iterator is invalidated after erase (Possible crash or corruption if reused)

### ISSUE THREAD

**Issue by shaovoon** [mohabouje/WinToast#85]
I noticed at https://github.com/mohabouje/WinToast/blob/master/src/wintoastlib.cpp#L794

The `_buffer` iterator is reused after erase(). According to C++ Reference and CPlusPlus webpage:

https://en.cppreference.com/w/cpp/container/map/erase

*"References and iterators to the erased elements are invalidated. Other references and iterators are not affected."*

https://cplusplus.com/reference/map/map/erase/

*"Iterators, pointers and references referring to elements removed by the function are invalidated."*

After the iterator is invalidated, it must not be used again. The iterator has to be assigned a fresh iterator from begin() again.

**Comment by mohabouje** [comment]
I don't understand the issue correctly. That specific line is a typical pattern to iterate and remove elements from standard containers. The method `std::map::erase` returns a valid [iterator](https://en.cppreference.com/w/cpp/container/map/erase) according to the standard:

```
1-3) Iterator following the last removed element.
```

The cppreference documentation shows an example of this same pattern:

```
#include <map>
#include <iostream>
 
int main()
{
    [std::map](https://en.cppreference.com/w/cpp/container/map)<int, [std::string](https://en.cppreference.com/w/cpp/string/basic_string)> c =
    {
        {1, "one" }, {2, "two" }, {3, "three"},
        {4, "four"}, {5, "five"}, {6, "six"  }
    };
 
    // erase all odd numbers from c
    for (auto it = c.begin(); it != c.end();)
    {
        if (it->first % 2 != 0)
            it = c.erase(it);
        else
            ++it;
    }
 
    for (auto& p : c)
        [std::cout](https://en.cppreference.com/w/cpp/io/cout) << p.second << ' ';
}
```
