### ISSUE TITLE
Feature Request: Push Notifications from Azure Notification Hub

### ISSUE THREAD

**Issue by cliftonlabrum** [mohabouje/WinToast#87]
It would be great if this library would allow showing server push notifications that come from Azure Notification Hub. These would be notifications sent from a server (even when the app is closed).

As far as I can tell, there is no way to use push notifications on Windows in a Flutter app. Perhaps this package should make that happen. 🙏🏼😊

**Comment by mohabouje** [comment]
Moved this feature request to https://github.com/mohabouje/WinToast/issues/86#issuecomment-1851544042
